### ISSUE TITLE
/results page - add design for survey result

### ISSUE THREAD

**Issue by miler350** [The-Wildfyre-Group/hopkins#22]
design element to show user key metrics for conditions they have:

- like me
- all black men
- all men

**Comment by khadijah-coakley** [comment]
Can you add the respective screen shot in the case that no data is in populated in the seed.

**Comment by miler350** [comment]
yup. adding now.

**Comment by miler350** [comment]
![screen shot 2016-08-31 at 9 14 38 pm](https://cloud.githubusercontent.com/assets/3248267/18151831/fc54699c-6fbf-11e6-90de-c3b028fa8e86.png)

**Comment by miler350** [comment]
This what the design shows now.
