### ISSUE TITLE
Design /admin/census

### ISSUE THREAD

**Issue by miler350** [The-Wildfyre-Group/hopkins#35]
just design 1 census table:

"title"... and then chart.

this will be used for all of the charts

**Comment by khadijah-coakley** [comment]
Error when trying to navigate to this page
http://www.awesomescreenshot.com/image/1547233/836fc775712347722790e648db2203a7

**Comment by miler350** [comment]
the page is attempting to find "year" for user which is based on user.birthdate..

so basically it's saying birthday for one or all of your users is nil

to fix:

`User.all.each { |user| user.update_attributes(birthdate:  Date.today - (18..80).to_a.sample}`
