### ISSUE TITLE
Share tool - is this working?

### ISSUE THREAD

**Issue by khadijah-coakley** [The-Wildfyre-Group/hopkins#56]
Where does the share object that is created on the homepage go? Is the photo populating?

Homepage version has buttons and form input field but can't see where this is saving or populating to....?

**Comment by dmitri-wm** [comment]
@khadijah-coakley not sure what exaclty unclear. 
Choose file, input name and click create share. You'll see prepopulated image like this one 
https://drive.google.com/file/d/0BxN2PVVfr4buMGp5eFlyZC1peDg/view?usp=drivesdk
Click on facebook icon and you'll share it https://drive.google.com/file/d/0BxN2PVVfr4budmRsVDhEXzNySk0/view?usp=drivesdk

All screenshots from live site. 

In terms of program -  we have Share model. After form submission created such model with assigned picture 'photo' . So you may access it with Share.last.photo.url

**Comment by khadijah-coakley** [comment]
@dmitri-wm is this in production only? And are you referring to the tool on the homepage ? When I tried it...nothing happened. No photo was pre-populated and no sharing buttons appeared.

**Comment by dmitri-wm** [comment]
@khadijah-coakley on production deployed current version of master branch.
Under production I mean: hopkins.herokuapp.com

If you tried locally it may happen so you didn't properly setup libraries for images processing, and this could cause server error. If so - check logs to see what the issue
