### ISSUE TITLE
Text message and email invites - Supposed to be functional?

### ISSUE THREAD

**Issue by khadijah-coakley** [The-Wildfyre-Group/hopkins#62]
Tested both, neither worked for me.
http://www.awesomescreenshot.com/image/1547281/fb09f5187e6b671dd6594ba1dc5365b7

**Comment by miler350** [comment]
the original box was on the share. i would just remove this box since the original share page was removed. doesn't make sense. it used to be functional - that is just an html box that you added after the other was removed. delete.

**Comment by khadijah-coakley** [comment]
@miler350 ??....I have not reviewed the commits. This is from the original design which proceeded any invite hookups so if it isn't function, it's likely was never functional. The design came first for the backend of this site ;-)
