### ISSUE TITLE
move photos to s3 / cdn

### ISSUE THREAD

**Issue by miler350** [The-Wildfyre-Group/hopkins#85]
photos making hp render slow. need to be moved to fast server.

**Comment by dmitri-wm** [comment]
@miler350 just need to optimize photos size. Having 5 photos 1.5 mb each - no cdn will help here. I've tried to decrease image size from 1.5 mb to 176 kb - in design looks no difference. In terms of site uploading will be great.

**Comment by miler350** [comment]
Yeah -- KC was going to optimize. ok.

**Comment by dmitri-wm** [comment]
@4acHuK use http://www.imageoptimizer.net/ or alternative service to change images till ~ 150 kb size in directory public/img.
